### PR TITLE
add option agentInstallAll, to control if install cluster-proxy addon…

### PR DESCRIPTION
**Pull request by ivan-cai**
… agent to all clusters

sometimes, we do not want install cluster-proxy to all clusters, but there is no this option

### CODE REVIEW

**Comment by ivan-cai** [comment]
@qiujian16 @yue9944882  Plz review

**Comment by qiujian16** [comment]
should we also update the helm chart?

/approve

**Comment by ivan-cai** [comment]
> should we also update the helm chart?
> 
> /approve

@qiujian16 Yes, I have update.  And what should I do for e2e?

**Comment by ivan-cai** [comment]
@qiujian16 @yue9944882 Plz merging this pr. Thx!

**Comment by qiujian16** [comment]
sorry, I missed this...

**Pull request merged**
